version: '3'

services:
  webapp:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SOLR_URL=http://solr:8983/solr
    depends_on:
      - solr
    volumes:
      - ./data:/app/data

  solr:
    image: solr:8.11
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr
    command:
      - solr-precreate
      - SC4021
      - /opt/solr/server/solr/configsets/basic_configs

volumes:
  solr_data: